s

diff --git a/apps/wanliz-utils/p4cherrypick b/apps/wanliz-utils/p4cherrypick
--- a/apps/wanliz-utils/p4cherrypick
+++ b/apps/wanliz-utils/p4cherrypick
@@ -27,6 +27,10 @@ Description:
 \t$desc
 EOF
 )
+if [[ $? != 0 || -z $new_changelist ]]; then
+    echo "Failed to create changelist" 
+    exit 1
+fi
 
 p4 unshelve -s $his_changelist -c $new_changelist || exit 1
 echo "Changes saved into $new_changelist"
